@url_base = http://localhost:5003/api/categoria
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoicG9ycmEiLCJleHAiOjE3NTAxMjI1OTF9.oczDcNVVCYN6SqTDfMK_UUV_yTvWvnXrcW5xuoZ4fhE

### Cadastrar categoria
POST {{url_base}}/cadastrar
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nome" : "Bebidas"
}

### Listar categorias
GET {{url_base}}/listar
Authorization: Bearer {{token}}